In [ ]:
!pip install pytorch

  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pytorch)


In [1]:
import torch

In [2]:
x = torch.rand(3)
x

tensor([0.3772, 0.1672, 0.0398])

In [3]:
torch.cuda.is_available()

True

In [5]:
y = torch.empty(2,2)
y

tensor([[1.5766e-19, 1.0256e-08],
        [1.0313e-08, 3.1471e+12]])

In [6]:
x = torch.ones(1,2,dtype=torch.float16)
print(x.size())


torch.Size([1, 2])


In [11]:
t = torch.tensor([1,2])
t.dtype

torch.int64

In [12]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)
y.add_(x) #inplace

tensor([[0.2528, 0.4871],
        [0.1275, 0.6842]])
tensor([[0.9668, 0.1010],
        [0.2181, 0.1860]])


tensor([[1.2196, 0.5881],
        [0.3457, 0.8702]])

In [17]:
i2 = torch.tensor([[1,0],[0,1]])
m1 = torch.tensor([[1,2],[3,4]])
m2 = torch.tensor([[5,6],[7,8]])

prod1 = torch.mul(m1,m2) #element-wise
prod3 = m1*m2 #element-wise
prod2 = torch.mm(m1,m2) #matrix multiplication
prod4 = m1 @ m2

print(prod1)
print(prod3)
print(prod2)
print(prod4)


tensor([[ 5, 12],
        [21, 32]])
tensor([[ 5, 12],
        [21, 32]])
tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [18]:
m3 = torch.rand(2,3,4) # batch of 2 mat, each of 3x4
m4 = torch.rand(2,4,5)

torch.bmm(m3,m4) #batch matrix multiplication

tensor([[[0.5701, 0.8112, 0.7359, 0.4411, 0.2203],
         [0.7976, 1.0001, 0.8157, 0.4742, 0.2371],
         [1.1969, 1.4814, 1.3023, 0.7619, 0.3571]],

        [[1.1802, 0.5986, 1.5367, 1.2145, 0.7499],
         [0.7754, 0.3717, 1.6330, 0.9047, 0.4786],
         [1.3394, 0.4378, 1.5679, 0.7081, 0.5375]]])

In [2]:
m5 = torch.tensor([1,2,3],dtype=torch.float)
m6 = torch.tensor([4,5,6],dtype=torch.float)

print(torch.dot(m5,m6),
torch.inner(m5,m6).squeeze())

torch.inner(m5,m6).item()  #converts into scalar

tensor(32.) tensor(32.)


32.0

In [27]:
torch.outer(m5,m6),torch.outer(m6,m5) #outer product is not commutative

(tensor([[ 4.,  5.,  6.],
         [ 8., 10., 12.],
         [12., 15., 18.]]),
 tensor([[ 4.,  8., 12.],
         [ 5., 10., 15.],
         [ 6., 12., 18.]]))

In [8]:
mat = torch.rand(4,4)
mat.view(16)

tensor([0.2456, 0.4998, 0.6461, 0.1159, 0.6581, 0.1321, 0.5146, 0.2411, 0.5170,
        0.2737, 0.5353, 0.5542, 0.1916, 0.8159, 0.4719, 0.2857])

In [9]:
mat.view(-1,8)

tensor([[0.2456, 0.4998, 0.6461, 0.1159, 0.6581, 0.1321, 0.5146, 0.2411],
        [0.5170, 0.2737, 0.5353, 0.5542, 0.1916, 0.8159, 0.4719, 0.2857]])

In [10]:
import numpy as np

a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [11]:
a.add_(1)


tensor([2., 2., 2., 2., 2.])

In [15]:
print(a,)
print(b,)
#here we can see that modifying 'a' also modifies 'b' coz they use the same location in memory

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [16]:
p = np.ones(5)
q = torch.from_numpy(p)
print(p)
print(q)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [17]:
if torch.cuda.is_available:
  device = torch.device("cuda")
  x = torch.ones(5,device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x+y
  print(z)
#the x+y oprn is performed on the GPU

tensor([2., 2., 2., 2., 2.], device='cuda:0')


In [19]:
z_arr = z.numpy() #error- numpy can only handle CPU tensors

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [21]:
z_arr = z.to("cpu").numpy()
z_arr

array([2., 2., 2., 2., 2.], dtype=float32)

requires_grad=True is a property of tensors that tells PyTorch to track all operations on that tensor so that it can compute gradients during backpropagation. This is crucial in tasks involving optimization and training machine learning models.

In [23]:
t = torch.ones(5,requires_grad=True)
print(t)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
